console.log("There once was a ship that was put to see")
console.log("Brandon Yurie was the name that be")
console.log("When told were to go")
console.log("It was 'Eagle Corps' where he found")
console.log("Would be his life turning tides")